spring:
    application:
        name: absoluta-backend
    profiles:
        active: test
    main:
        lazy-initialization: true
    jpa:
        open-in-view: true

springdoc:
  swagger-ui:
      tags-sorter: alpha