spring:
    application:
        name: control-api
    jpa:
        defer-datasource-initialization: true
        properties:
          hibernate:
              format_sql: true
              show_sql: true
    profiles:
        active: test
logging:
    level:
      org.hibernate.orm.jdbc.bind: trace
